name: move3d
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
 - python=3.11
 - pip
 - pip:
    - hydra-core==1.3.2
    - kineticstoolkit
    - opencv-python
    - numpy
    - beautifulsoup4
    - lxml
    - datetime