name: move3d
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - opencv
  - beautifulsoup4
  - lxml
  - hydra-core=1.3.2
  - kineticstoolkit
  - onnxruntime
  - pip
  - pip:
      - rtmlib    
      - imageio
      - -r requirements.txt